### ISSUE TITLE
Rotary push button

### ISSUE THREAD

**Issue by dakschnitzer** [miketeachman/micropython-rotary#3]
Hi Mike - thanks for sharing this.  I've gotten my rotary encoder to work beautifully with my esp32.  I was wondering whether you also have an implementation to read a button push from a rotary encoder with that feature.  Thanks!

**Comment by investigatronica** [comment]
I use [this](https://gist.github.com/jedie/8564e62b0b8349ff9051d7c5a1312ed7)
https://gist.github.com/jedie/8564e62b0b8349ff9051d7c5a1312ed7
