### ISSUE TITLE
uasyncio support

### ISSUE THREAD

**Issue by bseal84** [miketeachman/micropython-rotary#7]
Thank for your work on this. I admire people like yourself and only wish I was smart as those that keep these communities going!

I noticed one of your Future Ambitions was uasyncio support. Has their been any developments on this?

THanks again,

Brian

**Comment by miketeachman** [comment]
Hi Brian,
Sorry - I haven't started work on uasyncio support.    I still plan to do it, but I have some other MicroPython projects that have a higher priority.

**Comment by miketeachman** [comment]
a uasyncio example is now included in this commit:  https://github.com/miketeachman/micropython-rotary/commit/a0b988bd2c276878c66a6f451cd76f6762d30c45
